# Generated by Django 5.2.16 on 2026-08-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Kan de eigen character-info bekijken'),)},
        ),
    ]
