# Generated by Django 5.2.16 on 2026-08-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_general_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Kan de eigen EVE-gegevens bekijken'),)},
        ),
    ]
