# Generated by Django 5.2.16 on 2026-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Kan de eigen financiën bekijken'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
