# Generated by Django 5.2.16 on 2026-08-20 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijndashboard', '0004_permissienaam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleetsessie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('soort', models.CharField(choices=[('mining', 'Mining'), ('ratting', 'Ratting')], default='mining', max_length=10, verbose_name='Soort')),
                ('gestart', models.DateTimeField(auto_now_add=True, verbose_name='Gestart')),
                ('gestopt', models.DateTimeField(blank=True, null=True, verbose_name='Gestopt')),
                ('deelnemers', models.JSONField(blank=True, default=list, help_text='character-ids van iedereen die meedoet', verbose_name='Deelnemers')),
                ('boosters', models.JSONField(blank=True, default=list, help_text='wie een extra aandeel krijgt', verbose_name='Boosters')),
                ('booster_pct', models.PositiveSmallIntegerField(default=10, help_text='procent van de pot dat vooraf naar de boosters gaat', verbose_name='Aandeel booster')),
                ('begin', models.JSONField(blank=True, default=dict, verbose_name='Beginstand')),
                ('eind', models.JSONField(blank=True, default=dict, verbose_name='Eindstand')),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleetsessies', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
            ],
            options={
                'verbose_name': 'fleetsessie',
                'verbose_name_plural': 'fleetsessies',
                'ordering': ('-gestart',),
            },
        ),
    ]
