# Generated by Django 5.2.16 on 2026-08-20 14:42

from django.db import migrations


class Migration(migrations.Migration):
    """Het boosteraandeel eruit: de pot gaat gelijk over alle deelnemers."""


    dependencies = [
        ('mijndashboard', '0005_fleetsessie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetsessie',
            name='booster_pct',
        ),
        migrations.RemoveField(
            model_name='fleetsessie',
            name='boosters',
        ),
    ]
